# Generated by Django 4.2.29 on 2026-03-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faresetting',
            name='default_fare',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
